# Общие параметры животных
# Травоядные
animal.horse.weight=400.0
animal.horse.maxCount=20
animal.horse.speed=4
# Максимальная порция за один ход (в единицах веса)
animal.horse.maximumFoodLoad=60.0

animal.rabbit.weight=2.0
animal.rabbit.maxCount=150
animal.rabbit.speed=2
animal.rabbit.maximumFoodLoad=0.45

animal.deer.weight=300.0
animal.deer.maxCount=20
animal.deer.speed=4
animal.deer.maximumFoodLoad=50.0

animal.mouse.weight=0.05
animal.mouse.maxCount=500
animal.mouse.speed=1
animal.mouse.maximumFoodLoad=0.01

animal.goat.weight=60.0
animal.goat.maxCount=140
animal.goat.speed=3
animal.goat.maximumFoodLoad=10.0

animal.sheep.weight=70.0
animal.sheep.maxCount=140
animal.sheep.speed=3
animal.sheep.maximumFoodLoad=15.0

animal.boar.weight=400.0
animal.boar.maxCount=50
animal.boar.speed=2
animal.boar.maximumFoodLoad=50.0

animal.buffalo.weight=700.0
animal.buffalo.maxCount=10
animal.buffalo.speed=3
animal.buffalo.maximumFoodLoad=100.0

animal.duck.weight=1.0
animal.duck.maxCount=200
animal.duck.speed=4
animal.duck.maximumFoodLoad=0.15

animal.caterpillar.weight=0.01
animal.caterpillar.maxCount=1000
animal.caterpillar.speed=0
animal.caterpillar.maximumFoodLoad=0.0

#Только для травоядных
herbivore.base.eating.success.rate=1

# Хищники
animal.boa.weight=15.0
animal.boa.maxCount=30
animal.boa.speed=1
animal.boa.maximumFoodLoad=3.0

animal.wolf.weight=50.0
animal.wolf.maxCount=30
animal.wolf.speed=3
animal.wolf.maximumFoodLoad=8.0

animal.bear.weight=500.0
animal.bear.maxCount=5
animal.bear.speed=2
animal.bear.maximumFoodLoad=80.0

animal.eagle.weight=6.0
animal.eagle.maxCount=20
animal.eagle.speed=3
animal.eagle.maximumFoodLoad=1.0

animal.fox.weight=8.0
animal.fox.maxCount=30
animal.fox.speed=2
animal.fox.maximumFoodLoad=2.0

# === Вероятность, с которой хищник может съесть жертву ===
# Формат: predator.<хищник>.eats.<жертва>=вероятность (0.0 - 1.0)

# Утка
predator.duck.eats.caterpillar=0.5

# Волк
predator.wolf.eats.horse=0.1
predator.wolf.eats.rabbit=0.6
predator.wolf.eats.deer=0.15
predator.wolf.eats.mouse=0.8
predator.wolf.eats.goat=0.6
predator.wolf.eats.sheep=0.7
predator.wolf.eats.boar=0.15
predator.wolf.eats.buffalo=0.1
predator.wolf.eats.duck=0.4

# Лиса
predator.fox.eats.horse=0.0
predator.fox.eats.rabbit=0.7
predator.fox.eats.deer=0.0
predator.fox.eats.mouse=0.9
predator.fox.eats.goat=0.0
predator.fox.eats.sheep=0.0
predator.fox.eats.boar=0.0
predator.fox.eats.buffalo=0.0
predator.fox.eats.duck=0.6
predator.fox.eats.caterpillar=0.4

# Медведь
predator.bear.eats.horse=0.4
predator.bear.eats.boa=0.8
predator.bear.eats.deer=0.8
predator.bear.eats.mouse=0.9
predator.bear.eats.goat=0.7
predator.bear.eats.sheep=0.7
predator.bear.eats.boar=0.5
predator.bear.eats.buffalo=0.2
predator.bear.eats.duck=0.1
predator.bear.eats.fox=0.0
predator.bear.eats.rabbit=0.8

# Орёл
predator.eagle.eats.rabbit=0.9
predator.eagle.eats.mouse=0.9
predator.eagle.eats.duck=0.8
predator.eagle.eats.fox=0.1

# Удав
predator.boa.eats.rabbit=0.2
predator.boa.eats.duck=0.1
predator.boa.eats.mouse=0.4
predator.boa.eats.fox=0.15

# Эмодзи животных
wolf.emoji=🐺
sheep.emoji=🐑
rabbit.emoji=🐰
fox.emoji=🦊
bear.emoji=🐻
boar.emoji=🐗
horse.emoji=🐴
deer.emoji=🦌
goat.emoji=🐐
duck.emoji=🦆
eagle.emoji=🦅
mouse.emoji=🐭
buffalo.emoji=🐃
boa.emoji=🐍
caterpillar.emoji=🐛

