# Размер острова
island.width=20
island.height=100

# Длительность одного такта (в миллисекундах)
simulation.tick.delay=1000

# Максимальное количество ходов
simulation.max.turns=100

# Условие остановки: allDead, maxTurns, manual
simulation.stop.condition=allDead

# Начальное количество животных
initial.animal.horse=50
initial.animal.rabbit=200
initial.animal.fox=300
initial.animal.deer=100
initial.animal.mouse=500
initial.animal.caterpillar=2500
initial.animal.wolf=150
initial.animal.bear=150
initial.animal.eagle=30
initial.animal.goat=150
initial.animal.boa=150
initial.animal.boar=150
initial.animal.buffalo=75
initial.animal.sheep=180
initial.animal.duck=300


