# Размер острова
island.width=20
island.height=100

# Длительность одного такта (в миллисекундах)
simulation.tick.delay=1000

# Максимальное количество ходов (0 = бесконечно)
simulation.max.turns=0

# Условие остановки: allDead, maxTurns, manual
simulation.stop.condition=allDead

# Количество детёнышей при размножении
reproduction.count.horse=1
reproduction.count.rabbit=3
reproduction.count.fox=2
reproduction.count.deer=1
reproduction.count.mouse=5
reproduction.count.boa=4
reproduction.count.wolf=3
reproduction.count.bear=2
reproduction.count.eagle=1
reproduction.count.caterpillar=15
reproduction.count.goat=2
reproduction.count.boar=1
reproduction.count.buffalo=1
reproduction.count.sheep=1
reproduction.count.duck=5
